namespace ConsoleApp;

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("Hello, World!");
        Console.WriteLine("This is a console application generated by AGP CLI.");
        
        if (args.Length > 0)
        {
            Console.WriteLine($"Arguments: {string.Join(", ", args)}");
        }
    }
}
